---
# tasks file for network_upgrade

- name: remove inactive software
  block:

    - name: print information about the next task
      ansible.builtin.debug:
        msg:
          - "next task: remove inactive software"
          - "timeout is 1800 seconds"
      run_once: true

    - name: remove inactive software
      cisco.ios.ios_command:
        commands:
          - command: install remove inactive
            prompt: Do you want to remove the above files
            answer: y
      vars:
        ansible_command_timeout: 1800

  when: ansible_facts.net_iostype == 'IOS-XE'


- name: ensure maximum blocksize for tftp
  cisco.ios.ios_config:
    lines:
      - ip tftp blocksize 8192

- name: print information about the next task
  ansible.builtin.debug:
    msg:
      - "next task: upload compliant os"
      - "timeout is 3600 seconds"
  run_once: true

- name: upload compliant os
  cisco.ios.ios_command:
    commands:
      - command: copy tftp://{{ tftp_server }}/{{ compliant_os_file }} flash:/
        prompt: Destination filename
        answer: "\r"
  vars:
    ansible_command_timeout: 3600
  register: output
