---
# tasks file for network_upgrade

- name: gather facts
  cisco.nxos.nxos_facts:
    gather_subset: min

- name: include vars
  ansible.builtin.include_vars:
    file: "{{ ansible_network_os }}.{{ ansible_facts.net_model | regex_search('Nexus[0-9]+') | lower }}.yml"

- name: print compliance
  ansible.builtin.debug:
    msg: Running {{ ansible_facts.net_system }} is {{ ansible_facts.net_version }}.
         Compliant {{ ansible_facts.net_system }} is {{ compliant_os_version }}


- name: check if compliant os file is present in bootflash
  block:

    - name: check if the compliant os file is present in bootflash
      cisco.nxos.nxos_command:
        commands:
          - "dir bootflash: | include {{ compliant_os_file }}"
      register: flash_output

    - name: set fact
      ansible.builtin.set_fact:
        flash: "{{ flash_output['stdout'][0] }}"

  when:
    - not ansible_check_mode
    - ansible_facts.net_version != compliant_os_version
