---
# tasks file for network_upgrade

- name: gather facts
  cisco.ios.ios_facts:
    gather_subset: min

- name: set fact
  ansible.builtin.set_fact:
    compliant_os_version: "{{ catalyst_9k_compliant_os_version }}"
    compliant_os_file: "{{ catalyst_9k_compliant_os_file }}"
  when: "'C9' in ansible_facts.net_model"

- name: set fact
  ansible.builtin.set_fact:
    compliant_os_version: "{{ catalyst_2960_compliant_os_version }}"
    compliant_os_file: "{{ catalyst_2960_compliant_os_file }}"
  when: "'2960' in ansible_facts.net_model"

- name: set fact
  ansible.builtin.set_fact:
    compliant_os_version: "{{ catalyst_3850_compliant_os_version }}"
    compliant_os_file: "{{ catalyst_3850_compliant_os_file }}"
  when: "'3850' in ansible_facts.net_model"

- name: print compliance
  ansible.builtin.debug:
    msg: Running IOS is {{ ansible_facts.net_version }}.
         Compliant IOS is {{ compliant_os_version }}


- name: check if compliant os file is present in flash
  block:

    - name: check if the compliant os file is present in flash
      cisco.ios.ios_command:
        commands:
          - "show flash: | include {{ compliant_os_file }}"
      register: flash_output

    - name: set fact
      ansible.builtin.set_fact:
        flash: "{{ flash_output['stdout'][0] }}"

  when:
    - not ansible_check_mode
    - ansible_facts.net_version != compliant_os_version
